### ISSUE TITLE
Rubocop autocorect / autocorrect-all

### ISSUE THREAD

**Issue by KevinBerthier** [Shopify/vscode-ruby-lsp#847] opened 2023-10-19 10:43 UTC
### This feature is VS Code specific

- [X] VS Code specific

### Use case

When using format on save, rubocop seems to run with `--autocorrect` option, but some people might want to use  `--autocorrect-all` (for example frozen_string_literal comment is not added on safe autocorrect)

### Description

Add an option to set --autocorect-all

### Implementation

Could be a text field for rubocop options or a boolean for `rubocopAutocorrectAll`

**Comment by vinistock** [comment] 2023-10-30 18:06
Thank you for the feature suggestion! This is a duplicate of https://github.com/Shopify/ruby-lsp/issues/704, so I'm going to close in favour of that one to keep discussions centralized.

**Closed by vinistock** 2023-10-30 18:06 UTC
Labels: enhancement

**Comment by jhirn** [comment] 2024-01-25 18:20
> BTW you can add `SafeAutoCorrect: true` to a cop's configuration if you want it to always auto-correct. We do that in our Shopify's own config:

And there was much joy. So glad I found this posts. My chilly strings thank you greatly!
